import { createElement, type ReactNode } from "react";
import { QueryClient, QueryClientProvider, keepPreviousData } from "@tanstack/react-query";
import { cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { LOCAL_OPERATOR_INSTANCE as local } from "../src/lib/operator-read.js";
import { readCanonicalHealth, readCanonicalHealthDetail, useCanonicalHealth, useCanonicalHealthDetail } from "../src/hooks/useCanonicalHealth.js";
import { readCanonicalAttention, readDeliveredHumanUpdates, useCanonicalAttention, useDeliveredHumanUpdates } from "../src/hooks/useCanonicalAttention.js";
import { readConfigurationBrowser, useConfigurationBrowser } from "../src/hooks/useConfigurationBrowser.js";
import { readGatewayConnections, readSlackManifest, useGatewayConnections, useSlackManifest } from "../src/hooks/useGatewayConnections.js";

const at = "2026-10-04T12:00:00Z";
const finding = { schema: "openrig.health/v0alpha1", id: "health-a", detector: "queue-stall", category: "behavioral", scope: { type: "seat", rigId: "workshop", seatId: "builder" }, severity: "warning", confidence: "medium", status: "indeterminate", startedAt: at, lastObservedAt: null, window: { source: "mixed", startedAt: at, endedAt: at, limit: 20, retentionSeconds: 60 }, freshness: { state: "unavailable", evaluatedAt: at, newestSourceAt: null, maxAgeSeconds: 30, ageSeconds: null }, summary: "Inspect progress", threshold: "bounded window", explanation: "Missing evidence", suggestedInspection: "Read receipts", indeterminateReason: "source unavailable", evidence: [{ type: "queue-transition", sourceOrder: 0, observedAt: at, qitemId: "q-a", transitionId: 3, state: "delivered", actorSession: "builder", identityProvenance: null }, { type: "context-usage", sourceOrder: 1, observedAt: null, nodeId: "builder", sessionId: null, usedPercentage: null, available: false, fresh: false }], policyVersion: "v1", operatingPosture: { posture: "unknown", source: "unknown", context: null, binding: null, reason: "missing binding", grantsAuthority: false }, ceremony: { origin: "passive", stage: "indeterminate", lineageId: "lineage-a", basis: "bounded evidence", transitionIds: [3], context: [{ path: "mission.md", state: "unavailable", role: "mission" }], workflowReceipts: [], missingFacts: ["outcome"] } };
const health = { schema: "openrig.health-list/v0alpha1", evaluatedAt: at, total: 2, limit: 200, truncated: true, records: [finding], coverage: [{ source: "queue", evaluatedAt: at, status: "unavailable", partial: true, reason: "reader unavailable" }] };
const item = { id: "queue:q-a", kind: "action", summary: "Review", unblocks: "Builder", urgency: "high", at, scope: "workshop", project: { id: "project-a", root: "/example/project" }, source: "queue", recipient: "operator" };
const attention = { scope: "instance", readAt: at, items: [], sources: [{ source: "health", state: "partial", detail: "bounded" }, { source: "queue", state: "unavailable", detail: "offline" }], detail: { item, lines: ["Saved detail after closure"], files: [{ label: "Evidence", path: "/example/evidence" }] }, detailError: null };
const updates = { items: [{ qitemId: "q-u", summary: "Done", body: "Detailed delivery", humanDetail: "Outcome", destinationSession: "operator", sourceSession: "builder", tags: ["project:project-a"], evidenceRef: "receipt-a", deliveredAt: at, deliveryReceipt: "accepted-by-human-channel" }], limit: 20, truncated: true };
const config = { observedAt: at, home: null, readOnly: true, sources: [{ id: "file", state: "malformed", path: null, detail: "Cannot parse" }], entries: [{ key: "note", group: "general", value: null, defaultValue: null, defaultKnown: false, source: "unavailable", visibility: "withheld", reason: "Authored instructions withheld", scope: "instance", application: "restart" }], exclusions: ["credentials"] };
const gateway = { observedAt: at, home: null, pid: 123, settingsSource: null, settings: [{ key: "host.name", value: null, source: "unavailable" }], configSource: { state: "unavailable", path: null, sourceState: "malformed" }, configuration: null, running: { state: "failed", activatedAt: null, outboundReady: null, inboundReady: null, inboundState: "unverified", applied: "unverified" }, state: "unavailable", nextAction: "rig daemon logs", verification: { state: "indeterminate", at: null, actor: null }, registry: { state: "unavailable", path: null }, humans: [] };
const manifest = { yaml: "display_information: OpenRig", url: "https://api.slack.com/apps?new_app=1", scopes: ["chat:write"], events: ["message.channels"], manifest: { display_information: { name: "OpenRig", description: "Connector" }, features: { bot_user: { display_name: "OpenRig", always_online: false } }, oauth_config: { scopes: { bot: ["chat:write"] } }, settings: { event_subscriptions: { bot_events: ["message.channels"] }, interactivity: { is_enabled: true }, org_deploy_enabled: false, socket_mode_enabled: true, token_rotation_enabled: false } } };
const serve = (data: unknown) => { const mock = vi.fn(async (..._args: Parameters<typeof fetch>) => Response.json(data)); vi.stubGlobal("fetch", mock); return mock; };
const clients: QueryClient[] = [];
function wrapper() { const client = new QueryClient({ defaultOptions: { queries: { retry: false, placeholderData: keepPreviousData } } }); clients.push(client); return { client, wrapper: ({ children }: {children: ReactNode}) => createElement(QueryClientProvider, { client }, children) }; }
afterEach(() => { cleanup(); clients.splice(0).forEach(c => c.clear()); vi.unstubAllGlobals(); });

describe("canonical operator contracts", () => {
  it("retains bounded health coverage, evidence, posture and ceremony", async () => { const fetch = serve(health); expect(await readCanonicalHealth(local, { scopeType: "seat", scopeId: "builder", severity: "warning", status: "indeterminate" })).toEqual(health); expect(fetch.mock.calls[0]?.[0]).toBe("/api/health?limit=200&scope_type=seat&scope_id=builder&severity=warning&status=indeterminate"); });
  it("reads exact health identity and rejects different-entity detail", async () => { serve(finding); expect(await readCanonicalHealthDetail(local, "health-a")).toEqual(finding); await expect(readCanonicalHealthDetail(local, "health-b")).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("rejects invalid filter combinations and limits before HTTP", async () => { const fetch = serve(health); for (const filters of [{ scopeType: "seat" as const }, { scopeId: "x" }, { limit: 201 }, { limit: 0 }]) await expect(readCanonicalHealth(local, filters)).rejects.toMatchObject({ code: "invalid_request" }); expect(fetch).not.toHaveBeenCalled(); });
  it("rejects malformed nested health evidence", async () => { serve({ ...health, records: [{ ...finding, evidence: [{ ...finding.evidence[0], transitionId: "wrong" }] }] }); await expect(readCanonicalHealth(local)).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("retains partial attention sources and saved detail outside the active list", async () => { const fetch = serve(attention); expect(await readCanonicalAttention(local, "queue:q-a")).toEqual(attention); expect(fetch.mock.calls[0]?.[0]).toBe("/api/attention?item=queue%3Aq-a"); });
  it("retains explicit missing attention detail", async () => { const data = { ...attention, detail: null, detailError: "item not found" }; serve(data); expect(await readCanonicalAttention(local, "queue:missing")).toEqual(data); });
  it("rejects attention detail identity mismatch", async () => { serve(attention); await expect(readCanonicalAttention(local, "queue:other")).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("retains delivered update content/receipt and bounded list metadata separately", async () => { const fetch = serve(updates); expect(await readDeliveredHumanUpdates(local)).toEqual(updates); expect(fetch.mock.calls[0]?.[0]).toBe("/api/queue/human-updates?limit=20"); });
  it("rejects invalid delivered update bounds", async () => { const fetch = serve(updates); await expect(readDeliveredHumanUpdates(local, 101)).rejects.toMatchObject({ code: "invalid_request" }); expect(fetch).not.toHaveBeenCalled(); });
  it("retains config absence, defaults, visibility and source provenance", async () => { const fetch = serve(config); expect(await readConfigurationBrowser(local)).toEqual(config); expect(fetch.mock.calls[0]?.[0]).toBe("/api/config?view=browser"); });
  it("rejects raw configuration instead of treating it as a browser inventory", async () => { serve({ "daemon.port": 7433 }); await expect(readConfigurationBrowser(local)).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("retains gateway partial evidence and absence", async () => { const fetch = serve(gateway); expect(await readGatewayConnections(local)).toEqual(gateway); expect(fetch.mock.calls[0]?.[0]).toBe("/api/gateway/connections"); });
  it("retains running/configuration/dated verification and humans/bindings", async () => { const data = { ...gateway, configuration: { enabled: true, channel: "channel-a", inboundDestination: "operator", outboundDestinations: ["human:a"], postLevel: "info", interruptLevel: "high", botToken: "resolved", appToken: "missing" }, state: "unverified", running: { ...gateway.running, state: "active", outboundReady: true, inboundReady: false, applied: "matching" }, verification: { state: "ready-at-check", at, actor: "operator" }, registry: { state: "available", path: "/example/humans" }, humans: [{ browserKey: "safe-a", entityId: "human-a", address: "human:a", displayName: "A", class: "human", away: false, deliveryClass: "A", availability: "available", excluded: false, bindings: [{ browserKey: "safe-binding", kind: "slack", ref: "channel-a", role: "primary", handle: null, credentialReference: true }] }] }; serve(data); expect(await readGatewayConnections(local)).toEqual(data); });
  it("retains Slack manifest object and derived scopes/events", async () => { serve(manifest); expect(await readSlackManifest(local)).toEqual(manifest); });
  it("never fetches local projections when asked for remote-instance views", async () => { const remote = { kind: "remote-instance", hostId: "remote-b" } as const; const fetch = serve({}); for (const read of [() => readCanonicalHealth(remote), () => readCanonicalAttention(remote), () => readDeliveredHumanUpdates(remote), () => readConfigurationBrowser(remote), () => readGatewayConnections(remote), () => readSlackManifest(remote)]) await expect(read()).rejects.toMatchObject({ code: "unsupported_scope" }); expect(fetch).not.toHaveBeenCalled(); });
  it("gates remote hook truthfully without any local data", async () => { const fetch = serve(attention); const { wrapper: wrap } = wrapper(); const { result } = renderHook(() => useCanonicalAttention({ kind: "remote-instance", hostId: "remote-b" }), { wrapper: wrap }); expect(result.current.scopeSupported).toBe(false); expect(result.current.scopeError?.code).toBe("unsupported_scope"); expect(result.current.data).toBeUndefined(); expect(fetch).not.toHaveBeenCalled(); });
  it.each([
    ["health", () => useCanonicalHealth({ kind: "remote-instance", hostId: "remote-c" })],
    ["updates", () => useDeliveredHumanUpdates({ kind: "remote-instance", hostId: "remote-c" })],
    ["configuration", () => useConfigurationBrowser({ kind: "remote-instance", hostId: "remote-c" })],
    ["connections", () => useGatewayConnections({ kind: "remote-instance", hostId: "remote-c" })],
    ["manifest", () => useSlackManifest({ kind: "remote-instance", hostId: "remote-c" })],
  ])("gates remote %s hook and retains the exact remote cache scope", (_name, hook) => {
    const fetch = serve({}); const { client, wrapper: wrap } = wrapper();
    const { result } = renderHook(hook, { wrapper: wrap });
    expect(result.current.scopeError?.code).toBe("unsupported_scope"); expect(result.current.data).toBeUndefined(); expect(fetch).not.toHaveBeenCalled();
    expect(client.getQueryCache().getAll()[0]?.queryKey.slice(0, 3)).toEqual(["operator", "remote-instance", "remote-c"]);
  });
  it("retains every bounded health evidence variant, available coverage and full passive assessment", async () => {
    const data = { ...health, coverage: [{ source: "queue", evaluatedAt: at, unit: "transitions", limit: 20, total: 30, evaluated: 20, omitted: 10, partial: true, order: "latest-first" }], records: [{ ...finding,
      evidence: [
        ...finding.evidence,
        { type: "watchdog-history", sourceOrder: 2, observedAt: at, jobId: "job-a", historyId: "history-a", outcome: "posted", deliveryStatus: null },
        { type: "work-graph", sourceOrder: 3, observedAt: at, nodeType: "slice", nodeId: "slice-a", missionId: "mission-a", stage: "building", dependsOn: ["slice-b"] },
        { type: "topology-activity", sourceOrder: 4, observedAt: at, nodeId: "seat-a", sessionName: null, activity: null, activitySequence: null },
        { type: "occupant-model", sourceOrder: 5, observedAt: null, nodeId: "seat-a", occupantGeneration: null, runtime: null, model: null },
        { type: "lifecycle-receipt", sourceOrder: 6, observedAt: at, receiptId: "receipt-a", operation: "handoff", outcome: "observed" },
      ],
      operatingPosture: { posture: "delegated", source: "binding", context: { projectId: "project-a", phase: { value: "build", source: "mission.yaml" }, sources: ["project.yaml"], paths: { project: "/example/project", mission: "/example/mission" } }, binding: { id: "binding-a", scope: "mission", setAt: at, evidence: "operator-authored" }, reason: "explicit binding", grantsAuthority: false, members: [{ qitemId: "q-a", posture: "delegated", source: "binding", bindingId: "binding-a" }] },
      ceremony: { ...finding.ceremony, workflowReceipts: [{ trailId: "trail-a", instanceId: "workflow-a", stepId: "step-a", qitemId: "q-a", closureReason: "done", actor: "builder", at, evidence: { artifact: "outcome.md" } }], assessment: { result: { basis: "outcomes", conclusion: "indeterminate", outcomes: [{ id: "outcome-a", observedAt: at, evidenceRefs: ["outcome.md"] }], boundedAuthority: null, boundary: "mission", evidenceRefs: ["outcome.md"], missingFacts: ["judgment"] }, actor: "checker", at, transitionId: 4, identityProvenance: null } },
    }] }; serve(data); expect(await readCanonicalHealth(local)).toEqual(data);
  });
  it.each([
    ["configuration", () => readConfigurationBrowser(local), { ...config, entries: [{ ...config.entries[0], defaultKnown: "false" }] }],
    ["attention", () => readCanonicalAttention(local), { ...attention, sources: [{ source: "queue", state: "healthy", detail: "wrong contract" }] }],
    ["updates", () => readDeliveredHumanUpdates(local), { ...updates, items: [{ ...updates.items[0], deliveryReceipt: null }] }],
    ["connections", () => readGatewayConnections(local), { ...gateway, running: { ...gateway.running, applied: true } }],
    ["manifest", () => readSlackManifest(local), { ...manifest, scopes: "chat:write" }],
  ])("rejects malformed nested %s contracts", async (_name, read, data) => { serve(data); await expect(read()).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("uses exact detail keys without previous-entity placeholders and aborts navigation", async () => { const fetch = serve(finding); const { client, wrapper: wrap } = wrapper(); const { result, rerender } = renderHook(({ id }) => useCanonicalHealthDetail(local, id), { wrapper: wrap, initialProps: { id: "health-a" } }); await waitFor(() => expect(result.current.data?.id).toBe("health-a")); fetch.mockImplementation(() => new Promise(() => {})); rerender({ id: "health-b" }); expect(result.current.data).toBeUndefined(); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); const requestSignal = fetch.mock.calls[1]?.[1]?.signal; rerender({ id: "health-c" }); await waitFor(() => expect(requestSignal?.aborted).toBe(true)); expect(client.getQueryData(["operator", "local-instance", "health", "detail", "health-a"])).toEqual(finding); });
});
