import { createElement, type ReactNode } from "react";
import { QueryClient, QueryClientProvider, keepPreviousData } from "@tanstack/react-query";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { LOCAL_OPERATOR_INSTANCE as local } from "../src/lib/operator-read.js";
import { createProjectSelection, projectSliceDocumentUrl, projectSliceProofAssetUrl } from "../src/lib/project-read.js";
import { readProjectCatalog, useProjectCatalog } from "../src/hooks/useProjectCatalog.js";
import { readCanonicalScopes, useCanonicalScopes, readProjectSliceDetail, useProjectSliceDetail, readProjectSliceDocument } from "../src/hooks/useCanonicalScopes.js";
import { readExecutionView, useExecutionView } from "../src/hooks/useExecutionView.js";
import { catalog, execution, projects, scopes, sliceDetail } from "./project-contract-fixtures.js";
const a = { id: "a", root: "/books/a" }, b = { id: "b", root: "/books/b" };
const clients: QueryClient[] = [];
function wrapper() { const client = new QueryClient({ defaultOptions: { queries: { retry: false, placeholderData: keepPreviousData } } }); clients.push(client); return { client, wrapper: ({ children }: {children: ReactNode}) => createElement(QueryClientProvider, { client }, children) }; }
function serve(data: unknown, status = 200) { const mock = vi.fn(async (..._args: Parameters<typeof fetch>) => Response.json(data, { status })); vi.stubGlobal("fetch", mock); return mock; }
afterEach(() => { cleanup(); clients.splice(0).forEach(c => c.clear()); vi.unstubAllGlobals(); vi.useRealTimers(); });

describe("exact catalog project contracts", () => {
  it("keeps both required immutable selection fields", () => { const selection = createProjectSelection("a", "/books/a"); expect(selection).toEqual(a); expect(Object.isFrozen(selection)).toBe(true); });
  it("preserves two catalog roots, source metadata and unavailable entries", async () => { const data = { ...catalog, projects: [...projects, { ...projects[0], id: "broken", error: "Source missing" }] }; const fetch = serve(data); expect(await readProjectCatalog(local)).toEqual(data); expect(fetch.mock.calls[0]?.[0]).toBe("/api/scopes/projects"); });
  it("sends exact project/root for complete scopes including per-mission read errors", async () => { const fetch = serve(scopes()); expect(await readCanonicalScopes(local, a)).toEqual(scopes()); expect(fetch.mock.calls[0]?.[0]).toBe("/api/scopes?detail=1&project=a&projectRoot=%2Fbooks%2Fa"); });
  it("preserves native withdrawal despite proof pairing and legacy code PASS", async () => { const data = execution(); serve(data); const read = await readExecutionView(local, a, "trial"); expect(read).toEqual(data); expect(read.rows[0]?.readiness?.slices[0]?.readiness.items[0]?.state).toBe("withdrawn"); expect(read.rows[0]?.q4_ladder[0]?.reviewed.value).toBe(true); expect(read.rows[0]?.lifecycle_instances[0]?.boundary_obligations[0]?.receiptState).toBe("recorded"); });
  it("retains full lifecycle packets, acceptance, wakes, failures, reconciliation and sources", async () => { const data = execution(); const fetch = serve(data); expect(await readExecutionView(local, a, "trial")).toEqual(data); expect(fetch.mock.calls[0]?.[0]).toBe("/api/views/execution?project=a&projectRoot=%2Fbooks%2Fa&mission=trial"); });
  it("retains exact slice six-tab payload with full native judgment and partial proof", async () => { const fetch = serve(sliceDetail); expect(await readProjectSliceDetail(local, a, "trial", "one")).toEqual(sliceDetail); expect(fetch.mock.calls[0]?.[0]).toBe("/api/slices/one?project=a&projectRoot=%2Fbooks%2Fa&mission=trial"); });
  it("constructs exact document/proof URLs and retains served document identity", async () => {
    expect(projectSliceDocumentUrl(local, a, "trial", "one", "docs/Note A.md")).toBe("/api/slices/one/doc/docs/Note%20A.md?project=a&projectRoot=%2Fbooks%2Fa&mission=trial");
    expect(projectSliceProofAssetUrl(local, b, "trial", "one", "shot.png")).toBe("/api/slices/one/proof-asset/shot.png?project=b&projectRoot=%2Fbooks%2Fb&mission=trial");
    serve({ relPath: "docs/Note A.md", content: "Exact project document" });
    expect(await readProjectSliceDocument(local, a, "trial", "one", "docs/Note A.md")).toEqual({ relPath: "docs/Note A.md", content: "Exact project document" });
  });
  it("refuses document/proof path traversal, absolute paths and remote URL substitution", () => {
    for (const leaf of ["../private.md", "/private.md", "C:/private.md", "docs/../private.md", "", "docs\\private.md"]) expect(() => projectSliceDocumentUrl(local, a, "trial", "one", leaf)).toThrow();
    expect(() => projectSliceProofAssetUrl({ kind: "remote-instance", hostId: "host-b" }, a, "trial", "one", "shot.png")).toThrowError(/unavailable for remote/);
  });
  it("rejects incomplete or invalid selected project before fetch", async () => { const fetch = serve({}); for (const bad of [null, { id: "a" }, { root: "/books/a" }, { id: "a", root: "relative" }, { id: "../a", root: "/books/a" }]) { await expect(readCanonicalScopes(local, bad as typeof a)).rejects.toMatchObject({ code: "invalid_request" }); await expect(readExecutionView(local, bad as typeof a)).rejects.toMatchObject({ code: "invalid_request" }); await expect(readProjectSliceDetail(local, bad as typeof a, "trial", "one")).rejects.toMatchObject({ code: "invalid_request" }); } expect(fetch).not.toHaveBeenCalled(); });
  it("rejects missing/unsafe mission and slice before HTTP", async () => { const fetch = serve({}); await expect(readProjectSliceDetail(local, a, "", "one")).rejects.toMatchObject({ code: "invalid_request" }); await expect(readProjectSliceDetail(local, a, "trial", "../one")).rejects.toMatchObject({ code: "invalid_request" }); await expect(readExecutionView(local, a, "../trial")).rejects.toMatchObject({ code: "invalid_request" }); expect(fetch).not.toHaveBeenCalled(); });
  it("does not fall back after a changed root", async () => { const fetch = serve({ error: "project_changed", message: "Choose project again" }, 409); await expect(readExecutionView(local, { ...a, root: "/old/a" }, "trial")).rejects.toMatchObject({ code: "http", status: 409, serverCode: "project_changed" }); expect(fetch).toHaveBeenCalledTimes(1); expect(fetch.mock.calls[0]?.[0]).toContain("projectRoot=%2Fold%2Fa"); });
  it("rejects a different selected project/scopes root or execution mission in the response", async () => { serve(scopes("b")); await expect(readCanonicalScopes(local, a)).rejects.toMatchObject({ code: "invalid_contract" }); serve(execution("a", "other")); await expect(readExecutionView(local, a, "trial")).rejects.toMatchObject({ code: "invalid_contract" }); serve({ ...sliceDetail, missionId: "other" }); await expect(readProjectSliceDetail(local, a, "trial", "one")).rejects.toMatchObject({ code: "invalid_contract" }); });
  it.each([
    ["catalog", () => readProjectCatalog(local), { catalogPath: "x", projects: [{}] }],
    ["scopes", () => readCanonicalScopes(local, a), { ...scopes(), missions: [{ mission: "trial", slices: [{ ...scopes().missions[0]!.slices[0], readiness: { state: "ready" } }] }] }],
    ["execution", () => readExecutionView(local, a), { ...execution(), rows: [{ ...execution().rows[0], lifecycle_instances: [{ ...execution().rows[0]!.lifecycle_instances[0], boundary_obligations: [{ receiptState: "accepted" }] }] }] }],
    ["slice detail", () => readProjectSliceDetail(local, a, "trial", "one"), { ...sliceDetail, tests: { proofPackets: "wrong" } }],
  ])("rejects malformed nested %s data", async (_name, read, data) => { serve(data); await expect(read()).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("rejects same-named slice detail from another project root", async () => { serve({ ...sliceDetail, slicePath: "/books/b/missions/trial/slices/one" }); await expect(readProjectSliceDetail(local, a, "trial", "one")).rejects.toMatchObject({ code: "invalid_contract" }); });
  it("retains unavailable HTTP error separately from empty catalog and invalid JSON", async () => { serve({ error: "workspace_root_missing", message: "Root not configured" }, 409); await expect(readProjectCatalog(local)).rejects.toMatchObject({ code: "http", serverCode: "workspace_root_missing" }); serve({ catalogPath: "/books/workspace.yaml", projects: [] }); await expect(readProjectCatalog(local)).resolves.toMatchObject({ projects: [] }); vi.stubGlobal("fetch", vi.fn(async () => new Response("not json"))); await expect(readProjectCatalog(local)).rejects.toMatchObject({ code: "invalid_json" }); });
  it("gates remote scope and null selections without default-workspace requests", () => { const fetch = serve({}); const { wrapper: wrap } = wrapper(); const { result } = renderHook(() => [useProjectCatalog({ kind: "remote-instance", hostId: "host-b" }), useCanonicalScopes(local, null), useExecutionView(local, null), useProjectSliceDetail(local, a, null, "one")], { wrapper: wrap }); expect(result.current[0]?.scopeError?.code).toBe("unsupported_scope"); expect(fetch).not.toHaveBeenCalled(); });
  it("isolates equal mission/slice names across project IDs and changed roots", async () => { const fetch = serve(execution()); const { client, wrapper: wrap } = wrapper(); const { result, rerender } = renderHook(({ selection }) => useExecutionView(local, selection, "trial"), { wrapper: wrap, initialProps: { selection: a } }); await waitFor(() => expect(result.current.data?.rows[0]?.project).toBe("a")); fetch.mockImplementation(async () => Response.json(execution("b"))); rerender({ selection: b }); expect(result.current.data).toBeUndefined(); await waitFor(() => expect(result.current.data?.rows[0]?.project).toBe("b")); fetch.mockImplementation(() => new Promise(() => {})); rerender({ selection: { ...b, root: "/new/b" } }); expect(result.current.data).toBeUndefined(); expect(client.getQueryData(["operator", "local-instance", "projects", "a", "/books/a", "execution", "trial"])).toEqual(execution()); });
  it("aborts rapid mission switching and ignores late old-body results", async () => { let resolve!: (response: Response) => void; const fetch = vi.fn((..._args: Parameters<typeof globalThis.fetch>) => new Promise<Response>(done => { resolve = done; })); vi.stubGlobal("fetch", fetch); const { client, wrapper: wrap } = wrapper(); const { result, rerender } = renderHook(({ mission }) => useExecutionView(local, a, mission), { wrapper: wrap, initialProps: { mission: "trial" } }); const firstResolve = resolve; const firstSignal = fetch.mock.calls[0]?.[1]?.signal; fetch.mockImplementation(async () => Response.json(execution("a", "next"))); rerender({ mission: "next" }); await waitFor(() => expect(result.current.data?.rows[0]?.mission).toBe("next")); expect(firstSignal?.aborted).toBe(true); await act(async () => { firstResolve(Response.json(execution())); await Promise.resolve(); }); expect(result.current.data?.rows[0]?.mission).toBe("next"); expect(client.getQueryData(["operator", "local-instance", "projects", "a", "/books/a", "execution", "trial"])).toBeUndefined(); });
  it("isolates same-named slice details by project and mission", async () => {
    const fetch = serve(sliceDetail); const { client, wrapper: wrap } = wrapper();
    const { result, rerender } = renderHook(({ selection, mission }) => useProjectSliceDetail(local, selection, mission, "one"), { wrapper: wrap, initialProps: { selection: a, mission: "trial" } });
    await waitFor(() => expect(result.current.data?.slicePath).toBe(sliceDetail.slicePath));
    const bDetail = { ...sliceDetail, slicePath: "/books/b/missions/trial/slices/one", displayName: "B outcome" };
    fetch.mockImplementation(async () => Response.json(bDetail)); rerender({ selection: b, mission: "trial" }); expect(result.current.data).toBeUndefined();
    await waitFor(() => expect(result.current.data?.displayName).toBe("B outcome"));
    fetch.mockImplementation(() => new Promise(() => {})); rerender({ selection: b, mission: "next" }); expect(result.current.data).toBeUndefined();
    expect(client.getQueryData(["operator", "local-instance", "projects", "a", "/books/a", "slice-detail", "trial", "one"])).toEqual(sliceDetail);
    expect(client.getQueryData(["operator", "local-instance", "projects", "b", "/books/b", "slice-detail", "trial", "one"])).toEqual(bDetail);
  });
  it("retains source-unavailable rows and legacy/unknown proof states", async () => {
    const bad = { ...scopes(), missions: [{ mission: "trial", readiness: { ...execution().rows[0]!.readiness, state: "unknown", issues: ["Malformed child"] }, slices: [{ ...scopes().missions[0]!.slices[0], error: "Invalid frontmatter", readiness: undefined, status: null, stage: null, narrative: null, proofContract: [] }] }] };
    serve(bad); const data = await readCanonicalScopes(local, a); expect(data.missions[0]?.readiness?.state).toBe("unknown"); expect(data.missions[0]?.slices[0]?.error).toBe("Invalid frontmatter"); expect(data.missions[0]?.slices[0]?.readiness).toBeUndefined();
    const legacy = { ...sliceDetail, readiness: { ...sliceDetail.readiness, configured: false, state: "legacy", items: [], history: [], issues: [], policy: null } }; serve(legacy); expect((await readProjectSliceDetail(local, a, "trial", "one")).readiness.state).toBe("legacy");
  });
  it.each(["headers", "body"])("bounds selected-project %s reads", async stage => {
    vi.useFakeTimers(); const fetch = vi.fn((..._args: Parameters<typeof globalThis.fetch>) => stage === "headers" ? new Promise<Response>(() => {}) : Promise.resolve({ ok: true, status: 200, json: () => new Promise(() => {}), body: null } as unknown as Response)); vi.stubGlobal("fetch", fetch);
    const read = readCanonicalScopes(local, a).catch(error => error); await vi.advanceTimersByTimeAsync(5_000); expect(await read).toMatchObject({ code: "timeout" }); expect(fetch.mock.calls[0]?.[1]?.signal?.aborted).toBe(true); expect(vi.getTimerCount()).toBe(0);
  });
  it("rejects all remote readers without selected-source substitution", async () => {
    const fetch = serve({}); const remote = { kind: "remote-instance", hostId: "remote-b" } as const;
    for (const read of [() => readProjectCatalog(remote), () => readCanonicalScopes(remote, a), () => readExecutionView(remote, a, "trial"), () => readProjectSliceDetail(remote, a, "trial", "one"), () => readProjectSliceDocument(remote, a, "trial", "one", "SPEC.md")]) await expect(read()).rejects.toMatchObject({ code: "unsupported_scope" }); expect(fetch).not.toHaveBeenCalled();
  });
  it("keeps failed refresh error distinguishable from same-project cached facts", async () => { const fetch = serve(scopes()); const { wrapper: wrap } = wrapper(); const { result } = renderHook(() => useCanonicalScopes(local, a), { wrapper: wrap }); await waitFor(() => expect(result.current.data).toEqual(scopes())); fetch.mockImplementation(async () => Response.json({ error: "project_unavailable" }, { status: 409 })); await act(async () => { await result.current.refetch(); }); await waitFor(() => expect(result.current.error).toMatchObject({ code: "http", serverCode: "project_unavailable" })); expect(result.current.data).toEqual(scopes()); });
});
